# What's the name of the church?
title: "Generic Baptist Church of Peoria, IL"
# Give a brief description of the church
description: > # this means to ignore newlines until "baseurl:"
    Generic Baptist has been serving Peoria since 1981.
# Leave this alone
# Change this to the domain when you are finished and ready to publish.
url: "http://localhost:3000/" # the base hostname & protocol for your site | Switch to "http://biblebaptistmattoon.org/" Before running Glynn.  Afterwards change it back to http://localhost:4000/

# This is the path to the default images.  If you add different default images you can change them here.
default_header_image: "assets/default_header.jpg"
default_sermon_image: "assets/default_header.jpg"
default_blog_image: "assets/default_header.jpg"
default_about_image: "assets/default_header.jpg"
default_calendar_image: "assets/calendar_default.jpg"

# LEAVE EVERYTHING ELSE ALONE!!

# Build settings
markdown: kramdown
baseurl: "" # the subpath of your site, e.g. /blog

# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - bower_components

page_gen:
  - data: 'ministries'
    template: 'ministries'
    name: 'name'
    dir: 'ministries'
  - data: 'series'
    template: 'series'
    name: 'title'
    dir: 'series'
  - data: 'sermons'
    template: 'sermon'
    name: 'title'
    dir: 'sermons'
  - data: 'blog'
    template: 'blog-entry'
    name: 'title'
    dir: 'blog-posts'
  - data: 'abouts'
    template: 'aboutpage'
    name: 'title'
    dir: 'about-us'
  - data: 'events'
    template: 'event'
    name: 'event_name'
    dir: 'events'
  - data: 'abouts'
    template: 'about'
    name: 'title'
    dir: 'about-us'

